export const AUTH_ERRORS = {
  INVALID_CREDENTIALS: 'auth.INVALID_CREDENTIALS',
  USE_GOOGLE_AUTH: 'auth.USE_GOOGLE_AUTH',
  USER_NOT_FOUND: 'auth.USER_NOT_FOUND',
  ACCOUNT_NOT_VERIFIED: 'auth.ACCOUNT_NOT_VERIFIED',
  ACCOUNT_DELETED: 'auth.ACCOUNT_DELETED',
  EMAIL_ALREADY_EXIST: 'auth.EMAIL_ALREADY_EXIST',
  EMAIL_ALREADY_VERIFIED: 'auth.EMAIL_ALREADY_VERIFIED',
  PASSWORD_REQUIRED: 'auth.PASSWORD_REQUIRED',
  GOOGLE_ID_REQUIRED: 'auth.GOOGLE_ID_REQUIRED',
  INVALID_CODE: 'auth.INVALID_CODE',
  CODE_EXPIRED: 'auth.CODE_EXPIRED',
  INVALID_REFRESH_TOKEN: 'auth.INVALID_REFRESH_TOKEN',
  INVALID_OLD_PASSWORD: 'auth.INVALID_OLD_PASSWORD',
} as const;

export type AuthErrorCode = keyof typeof AUTH_ERRORS;
