"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { Activity,BarChart3,BookOpen,Building2,ChevronLeft,ChevronRight,FileAudio,FileText,Gauge,Globe2,GraduationCap,Library,Mic2,Settings,Users,X } from "lucide-react";
import type { Permission } from "@listenup/domain";
import { can } from "@listenup/domain/permissions";
import { useAdminSession } from "@/stores/admin-session";
import { cn } from "@/lib/utils";
const items:{label:string;href:string;icon:typeof Gauge;permission:Permission}[]=[{label:"Dashboard",href:"/dashboard",icon:Gauge,permission:"dashboard:view-assigned"},{label:"Students",href:"/students",icon:Users,permission:"student:view-assigned"},{label:"Teachers",href:"/teachers",icon:GraduationCap,permission:"teacher:view"},{label:"Courses",href:"/courses",icon:BookOpen,permission:"course:view-assigned"},{label:"Lessons",href:"/lessons",icon:Library,permission:"lesson:update"},{label:"Exercises",href:"/exercises",icon:FileAudio,permission:"exercise:update"},{label:"Attempts",href:"/attempts",icon:Activity,permission:"attempt:view-assigned"},{label:"Reports",href:"/reports",icon:BarChart3,permission:"report:view-assigned"},{label:"Media",href:"/media",icon:FileText,permission:"media:manage-assigned"},{label:"TTS Jobs",href:"/tts-jobs",icon:Mic2,permission:"tts-job:retry"},{label:"Landing Builder",href:"/landing",icon:Globe2,permission:"landing:update"},{label:"Site Settings",href:"/site-settings",icon:Building2,permission:"site-settings:update"},{label:"TTS Settings",href:"/tts-settings",icon:Settings,permission:"tts-settings:update"}];
export function AdminSidebar({mobile=false,onClose}:{mobile?:boolean;onClose?:()=>void}){const pathname=usePathname();const user=useAdminSession((s)=>s.user);const [collapsed,setCollapsedState]=usePersistentCollapsed();const width=collapsed&&!mobile?"w-[72px]":"w-60";return <aside className={cn("flex h-full flex-col bg-gradient-to-b from-[#071f33] to-[#061726] text-slate-200",!mobile&&"fixed inset-y-0 left-0 z-30 hidden border-r border-white/5 lg:flex",width)}><div className="flex h-18 items-center gap-3 border-b border-white/10 px-4"><span className="grid size-9 shrink-0 place-items-center rounded-lg bg-blue-600"><BookOpen className="size-5"/></span>{(!collapsed||mobile)&&<div><strong className="text-white">ListenUp</strong><span className="block text-[11px] text-blue-300">ADMIN CONSOLE</span></div>}{mobile&&<button className="ml-auto grid size-10 place-items-center" onClick={onClose} aria-label="Close menu"><X/></button>}</div><nav className="flex-1 space-y-1 overflow-y-auto p-2">{items.filter((item)=>can(user,item.permission)).map(({label,href,icon:Icon})=>{const active=pathname===href||pathname.startsWith(`${href}/`);return <Link onClick={onClose} key={href} href={href} title={collapsed?label:undefined} className={cn("flex min-h-10 items-center gap-3 rounded-lg px-3 text-sm font-medium",active?"bg-blue-600 text-white":"text-slate-300 hover:bg-white/5 hover:text-white")}><Icon className="size-4.5 shrink-0"/>{(!collapsed||mobile)&&label}</Link>})}</nav><div className="border-t border-white/10 p-3">{(!collapsed||mobile)&&<div className="mb-3 rounded-lg bg-white/5 p-3"><span className="text-[11px] text-slate-400">SIGNED IN AS</span><div className="mt-1 flex items-center justify-between"><strong className="text-sm text-white">{user?.role}</strong><span className="rounded bg-blue-500/20 px-2 py-0.5 text-[10px] text-blue-300">SECURE</span></div></div>}{!mobile&&<button onClick={()=>setCollapsedState(!collapsed)} className="flex min-h-10 w-full items-center justify-center rounded-lg hover:bg-white/5" aria-label={collapsed?"Expand sidebar":"Collapse sidebar"}>{collapsed?<ChevronRight/>:<ChevronLeft/>}</button>}</div></aside>}
function usePersistentCollapsed(){const [collapsed,setCollapsed]=useStateSafe();return [collapsed,(value:boolean)=>{setCollapsed(value);if(typeof window!=="undefined")localStorage.setItem("listenup-admin-sidebar",String(value))}] as const}
import { useState } from "react";
function useStateSafe(){return useState(()=>typeof window!=="undefined"&&localStorage.getItem("listenup-admin-sidebar")==="true")}
