"use client";
import { useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Search, SlidersHorizontal } from "lucide-react";
import { coursesApi } from "@/lib/api/client";
import { CourseCard } from "@/components/course/course-card";
import { EmptyState, ErrorState, LoadingSkeleton } from "@/components/ui/states";
import { PageHeader } from "@/components/ui/page-header";
export function CoursesPage() { const [search, setSearch] = useState(""); const [level, setLevel] = useState("All levels"); const [status, setStatus] = useState("All status"); const [sort, setSort] = useState("Recommended"); const query = useQuery({ queryKey: ["courses"], queryFn: () => coursesApi.list("") }); const filtered = useMemo(() => (query.data ?? []).filter((c) => (!search || c.title.toLowerCase().includes(search.toLowerCase())) && (level === "All levels" || c.level === level) && (status === "All status" || c.status === status)).sort((a, b) => sort === "Progress" ? b.progress - a.progress : a.title.localeCompare(b.title)), [query.data, search, level, status, sort]); return <div><PageHeader title="Explore Courses" description="Build listening skills with a path made for your level and goals." /><div className="surface mb-6 flex flex-col gap-3 p-4 md:flex-row"><label className="relative flex-1"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-slate-400" /><span className="sr-only">Search courses</span><input value={search} onChange={(e) => setSearch(e.target.value)} className="h-11 w-full rounded-lg border border-slate-200 pl-10 pr-3 text-sm outline-none focus:border-blue-500" placeholder="Search courses..." /></label><div className="grid grid-cols-2 gap-3 sm:grid-cols-3"><select value={level} onChange={(e) => setLevel(e.target.value)} aria-label="Level" className="h-11 rounded-lg border border-slate-200 px-3 text-sm"><option>All levels</option><option>Beginner</option><option>Intermediate</option><option>Advanced</option></select><select value={status} onChange={(e) => setStatus(e.target.value)} aria-label="Status" className="h-11 rounded-lg border border-slate-200 px-3 text-sm"><option>All status</option><option value="IN_PROGRESS">In progress</option><option value="COMPLETED">Completed</option><option value="NOT_STARTED">Not started</option></select><select value={sort} onChange={(e) => setSort(e.target.value)} aria-label="Sort" className="col-span-2 h-11 rounded-lg border border-slate-200 px-3 text-sm sm:col-span-1"><option>Recommended</option><option>Progress</option></select></div></div>{query.isLoading ? <LoadingSkeleton rows={3} /> : query.error ? <ErrorState message="Courses could not be loaded." onRetry={() => query.refetch()} /> : filtered.length ? <><div className="mb-4 flex items-center gap-2 text-sm text-slate-500"><SlidersHorizontal className="size-4" />Showing {filtered.length} courses</div><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{filtered.map((course) => <CourseCard key={course.id} course={course} />)}</div></> : <EmptyState title="No matching courses" description="Try clearing a filter or searching for another topic." />}</div>; }
